### ISSUE TITLE
Change components name / add description field

### ISSUE THREAD

**Issue by axelpezzo** [measuredco/puck#208]
There is a chance to have in future inside the Puck configuration, something in order to have an internal name for the component (the one used by puck to handle the component) and another title field, like a human readable field in order to display it inside the editor?

Now inside the editor I have only blocks named with the internal puck name as for eg: CardBlock ok ProductsSliderBlock but I looking for something like: "Card" or "Products Slider" and so on.

Nice to have: a description field to describe the components functionality.

**Comment by chrisvxd** [comment]
I quite like this suggestion. Something like the `label` field added to fields. I think there's value in that and it should be easy to add.

Adding a description field is harder because it requires new UI, which needs thinking about.

Mind splitting out the description request so this ticket can be marked as **Ready**?

**Comment by axelpezzo** [comment]
I think it could be great, thanks!

**Comment by chrisvxd** [comment]
The `label` API was added in #367, will be released in `v0.14.0` and available in canary
