### ISSUE TITLE
Load root content from IFrame and drag and drop in iframe

### ISSUE THREAD

**Issue by prashanthvdckap** [measuredco/puck#267]
Load root content from IFrame and drag and drop in iframe like we have in bigcommerce CMS builder

**Comment by chrisvxd** [comment]
Thanks for raising this @prashanthvdckap. Currently it's possible to render the entire Puck UI in an iframe, but it's not possible to render the preview in an iframe and the keep the remaining Puck UI outside of the iframe. Long explanation incoming 👇

There are various challenges with supporting this:

* iframes are generally poor for performance and can result in poor UX.
* It's difficult to support drag-and-drop between an iframe and host. Drag-and-drop is a core feature of Puck, so solving for this is important.

However, there are various advantages to iframes:

1. Style isolation, which can help prevent global style pollution into Puck's styles (Puck's styles are unlikely to leak out, because we follow [SUIT CSS principles](https://suitcss.github.io)).
2. Viewport previewing, see discussion https://github.com/measuredco/puck/discussions/72.

We don't yet have a concrete plan and haven't reached a conclusion as to whether we want to support iframes, but there are several different solutions have considered internally:

1. A new "add component" experience that doesn't rely on content being dragged from outside of the preview frame, like an "insert below" button.
2. Solving for drag and drop between iframes and their host, which may require patching https://github.com/hello-pangea/dnd.
3. Other non-iframe solutions for close the gap with iframes, like preview modals for viewport rendering.

Can you share why you want Puck to render in an iframe?

**Comment by chrisvxd** [comment]
Hey @prashanthvdckap. We now support iframes via #353.
