### ISSUE TITLE
Please add Tailwind css integration

### ISSUE THREAD

**Issue by Shani-Sinojiya** [measuredco/puck#286]
Please add Tailwind css integration

by [Shani Sinojiya](https://www.shanisinojiya.com)

**Comment by chrisvxd** [comment]
Hi @Shani-Sinojiya. Tailwind integration is already possible. Please see [this section](https://measured.co/blog/building-a-react-page-builder-an-introduction-to-puck#adding-tailwind) of our tutorial.

**Comment by siddiquiaffan** [comment]
Tailwind css works well unless and until we start using dynamic values in classNames.

## Example:
### Config:
```jsx
const config = {
    root: {
        render: ({ children }) => {
            return <div className="p-16">{children}</div>;
        },
    },
    components: {
        Button: {
    fields: {
        'Button Text': { type: 'text' },
        'Background Color': { type: 'text' }
    },
    defaultProps: {
        'Button Text': 'Click me',
        'Background Color': 'black'
    },
    render: (fields) => {
        return <>
            <Button className={
                cn(
                    `bg-[${fields['Background Color']}] hover:bg-[${fields['Background Color']}]/90`,
                )}>
                {fields['Button Text']}
            </Button>
        </>
    }
}
    },
};
```

The background won't be applied to the button.

@chrisvxd do you have any idea on this?

**Comment by Shani-Sinojiya** [comment]
I got a same problem.

**Comment by Shani-Sinojiya** [comment]
no, because tailwind css render css when server could send tailwind css.

**Comment by chrisvxd** [comment]
I've been exploring this, and both Puck and Tailwind are behaving as expected.

The issue is that you're relying on dynamic classes, which Tailwind is not aware of when deciding what CSS to include.

There are different ways to solve this -

## Add `safelist` to Tailwind config

If you know what Tailwind classes are likely to be included, then you can define a `safelist` in the Tailwind config that will always be included. i.e.

```ts
/** @type {import('tailwindcss').Config} */
module.exports = {
  ...
  safelist: [
    {
      pattern: /bg-.+/,
    },
  ],
};
```

## Inject the Tailwind script

If you really don't know what classes will be available and want to generate the classes dynamically, you'll need to inject the Tailwind script into your page.

Because this approach relies on a script, it doesn't play well with server-side rendering or SSG, and so I think it's better to be explicit.

```html
<script src="https://cdn.tailwindcss.com"></script>
```

If you're using Puck iframes, you'll need to use the new `iframe` override to also inject this into your iframe document

```ts
export function Editor() {
  return (
    <Puck
      overrides={{
        iframe: ({ children, document }) => {
          useEffect(() => {
            const script = document.createElement("script");
            script.setAttribute("src", "https://cdn.tailwindcss.com");
            document.head.append(script);
          }, [document]);
          return <>{children}</>;
        },
      }}
    />
  );
}
```

**Comment by Rados51** [comment]
In addition to `safelist`, you might need to use `extendTailwindMerge` from `tailwind-merge`.

```tsx
import { clsx, type ClassValue } from "clsx";
import { extendTailwindMerge } from "tailwind-merge";

const customTwMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      "font-size": [
        "text-sm__regular"
        "text-sm__medium"
      ],
    },
  },
});

export function cn(...inputs: ClassValue[]) {
  return customTwMerge(clsx(inputs));
}
```
