### ISSUE TITLE
Puck Editor Input Field Loose Focus while Typing if using plugin

### ISSUE THREAD

**Issue by sagarchoudhary96** [measuredco/puck#344]
I added a `TestPlugin` to my puck editor and after adding that, if i try to edit and input field value, on each character type the input field  looses focus. share a link to codesandbox for same: [Link](https://codesandbox.io/p/devbox/puck-editor-g9t8wk)

@chrisvxd please have a look at it and let me know if i'm missing something here.

**Comment by sagarchoudhary96** [comment]
@chrisvxd any updates on this please, this is making the editor not usable for us at the moment.

**Comment by chrisvxd** [comment]
@sagarchoudhary96 Looks like this is because you're re-setting the initial data. Puck doesn't currently support updating the data from an external source

Commenting out `onChange` fixes it:

```tsx
export function Client({ path, data }: { path: string; data: Data }) {
  const [initialData, setInitialData] = useState(data);
  return (
    <Puck
      config={config}
      data={initialData}
      // onChange={setInitialData}
      onPublish={async (data: Data) => {
        await fetch("/puck/api", {
          method: "post",
          body: JSON.stringify({ data, path }),
        });
      }}
      plugins={[TestPlugin]}
    />
  );
}
```

Related: https://github.com/measuredco/puck/issues/277#issue-2030979514

Going to close this. Feel free to comment if you need more support.

**Comment by xaviemirmon** [comment]
@sagarchoudhary96 I ran into this problem, too.  The new overrides (plugins or in `Puck`) mechanism causes a re-render. Because your data is being stored in a `useState()`, it's triggering a UI re-render after the initial re-render from Puck.  In our case setting it to a `useRef()` which doesn't update the UI fixed the problem for us.

**Comment by sagarchoudhary96** [comment]
Thanks @chrisvxd  @xaviemirmon  🙂
