### ISSUE TITLE
iframe style injection

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#409]
## Description

Users want to be able to inject styles into iframes for some use-cases.

We should leverage the iframe API to support this.

### Option 1

Consider leveraging the `initialContent` API from [`auto-frame-component`](https://github.com/measuredco/auto-frame-component):

```tsx
<Puck iframe={{
  initialContent="<!DOCTYPE html><html><head><style>body { background: hotpink; }</style></head><body><div></div></body></html>"
}} {/* ... */} />
```

### Option 2

Use a stripped back version of `initialContent` API from [`auto-frame-component`](https://github.com/measuredco/auto-frame-component):

```tsx
<Puck iframe={{
  head="<style>body { background: hotpink; }</style>"
}} {/* ... */} />
```

### Option 3

Add a dedicated parameters

```tsx
<Puck iframe={{
  style="body { background: hotpink; }"
  styleUrl="https://www.example.com/styles.css"
}} {/* ... */} />
```

**Comment by nicolas-angelo** [comment]
My first pick would be Opt 1 for maximum flexibility, though I'd be okay with Opt 2 as well.

**Comment by 4leite** [comment]
Ideally for my use-case, this would be dynamic, so updating the props would work (this is isn't clear given the name 'initialContent').

**Comment by nicolas-angelo** [comment]
After considering opening a PR for this, I came across some potential challenges based on my use case, particularly for working with tailwind.

For anyone who want to offer users the ability to set tailwind classes on components and compile JIT style at runtime - _mirroring_ the host styles could introduce classname conflicts. The typical way of using tailwind & JIT compilation w/ page builders is to [load the tailwind play CDN](https://tailwindcss.com/docs/installation/play-cdn) into the iframe:

But if the host app is also built with tailwind, then the host's globals.css file would clash with the css that tailwind play's script generates. There needs to be some style isolation.

I looked at the [code where the styles are being mirrored](https://github.com/measuredco/puck/blob/main/packages/core/components/AutoFrame/index.tsx), and after testing, realized that puck.css and global.css all get injected together in a style tag in the host's layout file.

Then I tried adding to @measured/puck's build script by additionally generating a module that exports a raw string of puck.css to do something like this:

```tsx
import puckStylesRaw from "../dist/raw-styles"

const AutoFrameComponent = React.forwardRef<HTMLIFrameElement, AutoFrameProps>(
  function ({ mirrorHostStyles: boolean, ...props }: AutoFrameProps, ref) {
  
    return (
      <Frame {...props} ref={ref}>
        <CopyHostStyles puckStyles={puckStylesRaw} mirrorHostStyles={mirrorHostStyles}... >
```

But it started feeling clunky and I realized I may be overcomplicating it. 😅
Ultimately, my goal was to keep the puck.css styles in the frame since they're needed, while making the rest of the host styles optional to include.

**Comment by chrisvxd** [comment]
@nicolas-angelo @4leite do you need style isolation in the Puck editor, or just in the final rendered output?

**Comment by nicolas-angelo** [comment]
@chrisvxd both. Although I know it's easier to manage styles for rendered output. The problem is the mirrored styles showing up in editor.

I plan on loading the tailwind play CDN in the editor and letting users enter dynamic classes, so I don't want the tailwind classes (or any classes from my host global stylesheet) ending up in the editor.

Im less concerned about isolating the puck.css classes because I don't really expect that to clash.

But preferably the editor can be used as a clean slate for styles.

**Comment by 4leite** [comment]
I have the above working. (Tailwind play CDN and users entering dynamic classes).
I actually don't need style isolation as I deal with that using tailwinds class prefix option.

**Comment by nicolas-angelo** [comment]
@4leite that dawned on me the other day but I still felt uneasy having the host styles mirrored in by default, even styles that weren't specifically tailwind generated. 

Awesome that you got it working though! Feel free to share you're approach if you don't mind it being public 😅

**Comment by 4leite** [comment]
You can see the gist of it there, although I haven't merged the class isolation and some bug fixes. 
https://github.com/Tohuhono/Oberon/tree/main/packages/ui/src/theme

**Comment by 4leite** [comment]
@chrisvxd  This is not a priority feature for me personally (I have solved it for my use case), I was more chiming in to document how I solved it for what seems like a similar use case.

**Comment by nicolas-angelo** [comment]
@chrisvxd yea I think I'm going to work off @4leite solution. But as far as general style injection feedback, I'd be happy with the following 

- renaming initialContent to 'content' or something that implies the value being dynamic and not initial
-  option to skip injecting host styles in iframe (except for the necessary puck styles)

**Comment by jarrrgh** [comment]
### Option 4
Include CSS in the Puck data? Something like:

```
{
  "content": [],
  "root": {
    "props": {
      "styles": "body { background: hotpink; }"
    }
  },
  "zones": {}
}
```

Reasoning: We are planning to have a CSS editor, which would update the styles in the data object. Currently we grab the styles prop and apply it inside the iframe body by overriding root render and placing a style element before children.

```
const config: Config = {
  root: {
    render: ({ children, styles }) => {
      return (
        <div>
          <style>{styles}</style>
          {children}
        </div>
      );
    },
  },
```

While this works, it would be better, if the styles got updated in the iframe head. In case of no iframe the styles could just go in the main window head I suppose...

**Comment by chrisvxd** [comment]
Great workaround @jarrrgh!

**Comment by SicParv1sMagna** [comment]
Does this prop will be included in <Puck.Preview /> component?

**Comment by jarrrgh** [comment]
I'm now also facing an issue due to Tailwind styles (and other styling) ending up inside the iframe. It would be helpful to have a way to control which styles are included in the iframe, in addition to the necessary Puck CSS, of course.

**Comment by xaviemirmon** [comment]
I've implemented a PR based on option 1.  While it isn't dynamic I thought it could be paired with the new onAction to help with that. e.g.
```tsx
<Puck
  iframe={{
    enabled: true,
    initialContent: '<!DOCTYPE html><html><head><style>body { background: hotpink; }</style></head><body><div id="styles"></div><div class="frame-root"></div></body></html>' 
  }}
 onAction={(action, appState, prevAppState) => {
   if (action.type === 'insert') { 
     document.getElementById(#styles).innerHTML( SYNC STYLES HERE)
   }
 }}
```
@4leite and @nicolas-angelo I'd be curious to know if this helps?

**Comment by chrisvxd** [comment]
Ended up taking a different approach to this as part of #543 via the new `iframe` override API:


### [`iframe` override API](https://puckeditor.com/v/canary/docs/api-reference/overrides/iframe)

Receives the iframe `document` as a prop. This enables you to inject your styles and manipulate the iframe document however you need.

```tsx
    <Puck overrides={{
      iframe: ({ children, document }) => {
        useEffect(() => {
          if (document) {
            // inject styles
          }
        }, [document]);

        return <>{children}</>;
      },
    }} />
 ```

Because this is an override, we can create plugins for common use-cases, like the new [`emotion-cache` plugin](https://github.com/measuredco/puck/tree/main/packages/plugin-emotion-cache).

Going to close this out as I think this API should cover most use-cases, but @ me if it's missing something.
