### ISSUE TITLE
create-app throws 404 without database.json

### ISSUE THREAD

**Issue by rezart** [measuredco/puck#44]
I followed the intrusions and created a new app using

```npx create-puck-app my-app```

Running `yarn dev` and accessing http://localhost:3000 throws 404. Looking at `app/[...puckPath]/page.tsx` it looks like it throws a 404 when database.json is not found. I tried creating an empty file but the same issue persists. What should go in this file when bootstrapping the editor for the first time?

**Comment by chrisvxd** [comment]
Hi @rezart! This is currently by design, but agree this is confusing. The app will 404 if the page doesn't exist.

To create a page, go to `/edit` and hit publish (FYI you can do this for any URL thanks to Next.js catch-alls).

Having said that, we should probably include a default page in the database so I'll keep this issue open.

**Comment by chrisvxd** [comment]
Implemented in #45 by @matthewlynch. Thank you!
