### ISSUE TITLE
Load and show live data on client side

### ISSUE THREAD

**Issue by mohanyadav** [measuredco/puck#509]
First of all thank you for developing such a wonderful visual editor

We currently have an analytics widget which the admin can drag and drop when creating pages (please refer below SS). In the current setup live data is fetched in the admin Puck editor using `resolveData()`

![image](https://github.com/measuredco/puck/assets/11350400/3cfa0e28-4ec1-4a71-92c0-8a7196325d54)

But in the client side the widget does not refresh the analytics data and only shows the static data. Is there a way to refetch the data on the client in Puck component?

**Comment by chrisvxd** [comment]
Hi @mohanyadav, and thank you. Apologies for the slow response.

You might be better off fetching your data inside the component with a `useEffect` hook, rather than, or in combination with the `resolveData` method.

resolveData is designed to populate the props with data. You can use the [`resolveAllData` API](https://puckeditor.com/docs/integrating-puck/dynamic-props#triggering-resolvedata) to force it to update, but for your use-case, I suspect requesting data client side within the component is the better solution.

I'll close this, but feel free to reply if you're still having trouble.
