### ISSUE TITLE
Puck shouldn't add extraneous elements

### ISSUE THREAD

**Issue by par5er** [measuredco/puck#71]
I am trying to make an email template editor using Puck and [React Email](https://react.email/docs/components/html). However, Puck is adding a few extra elements between the root element and the component (see screenshot) which is causing styles such as:
```
#my-email-container {
  display: flex;
  flex-flow: column;
  align-items: center;
}
```

to not work as expected.

![](https://github.com/measuredco/puck/assets/106308270/06a3d56f-21ea-48f9-a2f1-201a15529dda)

Example code:
```tsx
const config = {
  root: {
    render({ children }) {
      return <div className="my-email-container">{children}</div>;
    },
  },
  components: {
    Button: {
      fields: { ... },
      render({ content, url, bgColor }) {
        return (
          <Button
            pX={20}
            pY={12}
            href={url}
            style={{ background: bgColor, color: "#000" }}
          >
            {content}
          </Button>
        );
      },
    },
  },
};

const initialData = {
  root: {
    title: "Title",
  },
  content: [],
};

export default function EmailEditorPage() {
  return (
        <Puck
          config={config}
          data={initialData}
        />
  );
}
```

**Comment by chrisvxd** [comment]
Hey @par5er! An email builder is a great use-case.

The elements exist partially because that's how the drag-and-drop (well, react-beautiful-dnd) works. There _might_ be ways to change the behaviour, but it's not something I've explored and my suspicion is that it's non-trivial.

I'd be interested to know what exactly you're trying to achieve stylistically to see if there's another way we can get Puck to behave for you.

**Comment by chrisvxd** [comment]
Closing in favour of #455
